{
 "title": "MyDataSource",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "CAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{category=~\"requests\", subcategory=\"rd_total\"}) ",
     "legendFormat": "Read (%)"
    },
    {
     "expr": "  scalar(ocf_percentage{category=~\"requests\", subcategory=\"wr_total\"}) ",
     "legendFormat": "Write (%)"
    }
   ]
  },
  {
   "title": "Read Cache Hits (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{category=~\"requests\", subcategory=\"rd_hits\"}) /   (0.001+scalar(ocf_percentage{category=~\"requests\", subcategory=\"rd_total\"}))  * 100",
     "legendFormat": "Read Hits (%)"
    }
   ]
  },
  {
   "title": "Write Cache Hits (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{category=~\"requests\", subcategory=\"wr_hits\"}) /   (0.001+scalar(ocf_percentage{category=~\"requests\", subcategory=\"wr_total\"})) * 100",
     "legendFormat": "Write Hits (%)"
    }
   ]
  },
  {
   "title": "Cache Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{category=~\"usage\", subcategory=\"occupancy\"}) ",
     "legendFormat": "Occupancy (%)"
    }
   ]
  },
  {
   "title": "OCF Reads (MBps)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"cas1-1\"}[5s])/1024/1024",
     "legendFormat": "{{ bdev_name }} Reads"
    }
   ]
  },
  {
   "title": "OCF Writes (MBps)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"cas1-1\"}[5s])/1024/1024",
     "legendFormat": "{{ bdev_name }} Writes"
    }
   ]
  },
  {
   "title": "Cache Laundry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  scalar(ocf_percentage{category=~\"usage\", subcategory=\"clean\"}) ",
     "legendFormat": "Clean Lines (%)"
    },
    {
     "expr": "  scalar(ocf_percentage{category=~\"usage\", subcategory=\"dirty\"}) ",
     "legendFormat": "Dirty Lines (%)"
    }
   ]
  },
  {
   "title": "Blocks written to CAS (4K blocks)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "  irate(ocf_count{category=~\"blocks\", subcategory=\"volume_wr\"}[2s]) ",
     "legendFormat": "{{ bdev_name }} Writes"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Average Queue Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{device=~\"nvme0n1|md0\"}[5s])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"nvme0n1|md0\"}[5s]) /\r (irate(node_disk_read_completed_total{device=~\"nvme0n1|md0\"}[5s])+0.01)",
     "legendFormat": "{{ device }} Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"nvme0n1|md0\"}[5s]) /\r (irate(node_disk_writes_completed_total{device=~\"nvme0n1|md0\"}[5s])+0.01)",
     "legendFormat": "{{ device }} Write"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[5s]) + avg_over_time(node_memory_Cached_bytes[5s]) + avg_over_time(node_memory_Buffers_bytes[5s])) / avg_over_time(node_memory_MemTotal_bytes[5s])))",
     "legendFormat": "Percent Usage (%)"
    },
    {
     "expr": "(avg_over_time(node_memory_MemTotal_bytes[5s]) - (avg_over_time(node_memory_MemFree_bytes[5s]) + avg_over_time(node_memory_Cached_bytes[5s]) + avg_over_time(node_memory_Buffers_bytes[5s])))/1024/1024/1024",
     "legendFormat": "Total Used (GB)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Block Device Throughput (MBps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_read_bytes_total{device=~\"nvme0n1|cas1-1\"}[5s]))/1024/1024",
     "legendFormat": "{{ device }}  Reads"
    },
    {
     "expr": " (irate(node_disk_written_bytes_total{device=~\"nvme0n1|cas1-1\"}[5s]))/1024/1024",
     "legendFormat": "{{ device }}  Writes"
    },
    {
     "expr": "(irate(node_disk_read_bytes_total{device=~\"md0\"}[5s]))/1024/1024/8",
     "legendFormat": "{{ device }}  Reads"
    },
    {
     "expr": " (irate(node_disk_written_bytes_total{device=~\"md0\"}[5s]))/1024/1024/8",
     "legendFormat": "{{ device }}  Writes"
    }
   ]
  },
  {
   "title": "CPU 0 Usage",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 6, "x": 17, "y": 21 },
   "targets": [
    {
     "expr": " (irate(node_cpu_seconds_total{mode=~\"system\"}[5s])*100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"nvme0n1|md0|cas1-1\"}[5s])",
     "legendFormat": "{{ device }} Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"nvme0n1|md0|cas1-1\"}[5s])",
     "legendFormat": "{{ device }} Writes"
    }
   ]
  },
  {
   "title": "Latency (us)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{device=~\"nvme0n1|md0\"}[5s]) /  (irate(node_disk_reads_completed_total{device=~\"nvme0n1|md0\"}[5s])+0.01) * 1000 * 1000",
     "legendFormat": "{{ device }}  read lat"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{device=~\"nvme0n1|md0\"}[5s]) /  (irate(node_disk_writes_completed_total{device=~\"nvme0n1|md0\"}[5s])+0.01) * 1000 * 1000",
     "legendFormat": "{{ device }} write lat"
    }
   ]
  },
  {
   "title": "CPU IOWait Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 37 },
   "targets": [
    {
     "expr": " (irate(node_cpu_seconds_total{mode=~\"iowait\"}[5s])*100)"
    }
   ]
  }
 ]
}